### ISSUE TITLE
Support running on worker nodes

### ISSUE THREAD

**Issue by ariselseng** [comsave/nginx-proxy-letsencrypt#1]
It would be great if this also supported running on worker nodes.
In my project I will load balance around 30 nginx instances with round-robin dns. I need the combined total bandwidth of all the nodes, and 30 manager nodes is not ideal.

Could you lay of the potensial problems with making this project support worker nodes as well? Essensially the listening mechanism needs to change right?

**Comment by JoeriVeder** [comment]
Hi @cowai , Sadly I could not find a way to get the workers to listen for all swarm events. Currently I tap into the docker socket to retrieve the events from it. The main issue was that only manager nodes receive all swarm events and worker nodes only show their own events.

Why would you run 30 nginx instances if one could load balance it across your entire swarm?

The modified docker-gen that this project uses uses the swarm ingress network to balance all requests.

If you add a constraint on the nginx-proxy-letsencrypt-swam container to only run on manager nodes it will recreate on node failure if you have multiple managers.

FYI:
In our setup we use haproxy to redirect all traffic to the swarm manager that is currently hosting the nginx-proxy-letsencrypt-swarm container.

**Comment by ariselseng** [comment]
@JoeriVeder Looks like we need a separate service running on the managers that will listen for events and dump it to a websocket or some other pubsub. Maybe redis? And then all nginx containers would need to wait for events.

The reason I need nginx on all workers, is that I am making an HLS CDN and I need all the bandwidth I can. Having a few managers will be too limiting. As the load is not CPU-intensive, but bandwidth intensive.

**Comment by JoeriVeder** [comment]
@cowai I have another project https://github.com/comsave/docker-swarm-watcher this project can listen to socket events and it exposes an endpoint. Using the command yml file you can run any command depending on the event that was fired.

This project has already been added to the nginx-proxy-letsencrypt-swarm but it's currently not being used.

Hope this helps.

**Comment by ariselseng** [comment]
Thanks.
I actually might pick this up and find a solution.
